language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install pytest Twisted coveralls pytz . --use-mirrors"
script:
  - "coverage run $(which trial) test_parsley"
  - "coverage run -a $(which trial) ometa"
  - "coverage run -a $(which py.test) examples"
after_success:
  - "coveralls"
  
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.org#parsley
    on_success: always
    on_failure: always
