language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

matrix:
  allow_failures:
    # 2.6 doesn't have SkipTest, so it's going to fail.
    - python: 2.6

install:
  - "bash .travis.install"
  - "pip install pytest coveralls pytz ."
script:
  - "coverage run $(which py.test) ."
after_success:
  - "coveralls"
